services:
  cross:
      image: node:24-alpine
      working_dir: /app
      volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./eslint.config.mjs:/app/eslint.config.mjs
      - ./.swcrc:/app/.swcrc
      - ./.env:/app/.env
      - ./tsconfig.build.json:/app/tsconfig.build.json
      - ./tsconfig.json:/app/tsconfig.json
      ports:
        - 8900:3000
      entrypoint: ["/bin/sh", "-c"]
      command: ["npx nodemon --watch src --ext ts,sql --delay 1 --legacy-watch --polling-interval 3000 --exec \"nest build -b swc && node dist/main\""]
      mem_limit: 256m
      networks: [cross-network]
  garage:
      image: dxflrs/garage:v2.1.0
      container_name: garage
      volumes:
        - ./garage.dev.toml:/etc/garage.toml:ro
        - ./garage/garage_meta:/var/garage/meta
        - ./garage/garage_data:/var/garage/data
        - ./garage/snapshots:/var/garage/snapshots
      ports:
        - 3900:3900
        - 3901:3901
        - 3902:3902
        - 3903:3903
      networks: [cross-network]
  garage-ui:
    image: khairul169/garage-webui:latest
    container_name: garage-ui
    volumes:
      - ./garage.dev.toml:/etc/garage.toml:ro
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
      AUTH_USER_PASS: "admin:$$2y$$10$$EFSJVCbj9SettqwmQ2LhxeUfYPZDFLYQQsgjhOjgWsE9osAEzSIPe"
    ports:
      - 3909:3909
    depends_on: [garage]
    networks: [cross-network]

networks:
  cross-network:
    driver: bridge